### ISSUE TITLE
Add React imports to App.tsx and index.tsx

### ISSUE THREAD

**Issue by anoushk1234** [coral-xyz/xnft-quickstart#5]
<img width="943" alt="Screenshot 2022-11-01 at 10 07 48 PM" src="https://user-images.githubusercontent.com/32778608/199287563-64bfc8d4-c551-4256-84c4-3da32ae4f59f.png">

Minor issue but need to add React as an import otherwise it gives this error

**Comment by wentokay** [comment]
closing for now as this shouldn't be necessary due to [babel-preset-expo](https://www.npmjs.com/package/babel-preset-expo) automatically importing react

<img width="779" alt="Screenshot 2023-01-14 at 15 41 51" src="https://user-images.githubusercontent.com/101902546/212480290-fb405f3b-d680-4101-b3f8-f8d498cabeff.png">

but please reply and we can reopen the issue if you're still facing problems
